apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-django
  labels:
    app: {{ .Release.Name }}-django
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-django
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-django
    spec:
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          # Несекретні змінні — з ConfigMap, секретні (SECRET_KEY, POSTGRES_PASSWORD) — із Secret
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
