apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}-django
type: Opaque
# stringData — значення передаються у відкритому вигляді, Kubernetes сам кодує їх у base64.
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
